# NumPy Operations

In [4]:
import numpy as np

In [18]:
arr = np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
arr - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [36]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr / arr # here it will throw a division by zero error but it shows as warning in case of numpy array

C:\Users\pns86\AppData\Local\Temp\ipykernel_7832\814332230.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # here it will throw a division by zero error but it shows as warning in case of numpy array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [38]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [42]:
sqr_arr = np.square(arr)

In [44]:
sqr_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [46]:
np.sqrt(sqr_arr)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [50]:
np.max(arr)

10

In [52]:
np.min(arr)

0

In [54]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [60]:
np.log(arr) # as log 0 is -infinity it throws a warning divide by zero

C:\Users\pns86\AppData\Local\Temp\ipykernel_7832\140266342.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # as log 0 is -infinity it throws a warning divide by zero


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])