NumPy Arrays

In [2]:
import numpy as np

In [4]:
my_lst = [1,2,3]

In [16]:
arr1 = np.array(my_lst)

In [18]:
arr1

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
mat1 = np.array(my_mat)

In [14]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.arange(1,101,2)  #parameters for arange function (start,end,step up)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.zeros((2,5)) #first paramter is for rows and second one is for coloumns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.linspace(0,10,3)  # here btw 2 points placed on linear plane it will take 3rd parameter will act as no. of stops between them

array([ 0.,  5., 10.])

In [64]:
# Identity Matrices 

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
np.random.rand(5)

array([0.72760305, 0.60648526, 0.81518314, 0.19283311, 0.15045591])

In [78]:
np.random.rand(5,3)   # 2 parameters will give me a 2D array with random values

array([[0.19314163, 0.88633545, 0.01039711],
       [0.83003009, 0.20942406, 0.88324293],
       [0.31834383, 0.20752845, 0.97805984],
       [0.16535144, 0.44956785, 0.3244171 ],
       [0.52989356, 0.73666856, 0.92795155]])

In [80]:
np.random.randn(3)

array([-1.87934202,  0.30884021, -0.85470336])

In [82]:
np.random.randn(2,3)

array([[ 0.19953331,  0.78756081, -0.18663676],
       [-0.18050586, -1.43064467, -0.28716691]])

In [86]:
np.random.randint(1,101,2) # 3rd argument will be no. of values to be selected on a random basis between inclusive starting and exclusive ending range

array([37, 25])

Reshape an array

In [91]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
random_arr = np.random.randint(1,50,10)
random_arr

array([ 6,  5, 30, 39, 31, 12,  6, 18, 14,  1])

In [103]:
arr.reshape(5,5)  # here we cannot reshape an array beyond it's total no. of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
random_arr.reshape(2,5)

array([[ 6,  5, 30, 39, 31],
       [12,  6, 18, 14,  1]])

In [119]:
# Max and Min in an array

random_arr.max()

39

In [109]:
random_arr.min()

1

In [117]:
random_arr.argmax()  # this will return the index of max element in an array

3

In [115]:
random_arr.argmin()

9

In [121]:
# to convert a 1D array to 2D array

arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [125]:
arr.shape  # now arr is converted as a 2D array

(5, 5)

In [127]:
# to Know the datatype of elements in an array

arr.dtype

dtype('int32')

In [129]:
arr1 = np.arange(0,11)

In [131]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
arr1[3]

3

In [137]:
arr1[2:7]

array([2, 3, 4, 5, 6])

In [143]:
arr1[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
arr1[:5] = 100

In [147]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [151]:
arr1 = np.arange(0,11)

In [153]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [155]:
arr2 = arr1[:6]

In [157]:
arr2

array([0, 1, 2, 3, 4, 5])

In [159]:
arr2[:] = 2

In [163]:
arr2

array([2, 2, 2, 2, 2, 2])

In [167]:
arr1   # here it has changed the values of orginal array elements

array([ 2,  2,  2,  2,  2,  2,  6,  7,  8,  9, 10])

In [179]:
arr1_copy = arr1.copy()   # make use of this coopy function to avoid above problem

In [181]:
arr1_copy

array([ 2,  2,  2,  2,  2,  2,  6,  7,  8,  9, 10])

In [183]:
arr1_copy[:3] = 4

In [185]:
arr1_copy

array([ 4,  4,  4,  2,  2,  2,  6,  7,  8,  9, 10])

In [187]:
arr1

array([ 2,  2,  2,  2,  2,  2,  6,  7,  8,  9, 10])

In [199]:
arr_2d = arr.copy()

In [201]:
arr_2d[2][2]  # to find element index at this position in 2D array using double square brackets

12

In [195]:
# or else we can also use comma seperated args passed as row and column respectively as below

In [203]:
arr_2d[2,1]

11

In [207]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [215]:
arr_2d[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [221]:
# Conditional Selection

In [241]:
arr_rand = np.random.randint(1,11,10)

In [243]:
arr_rand

array([5, 2, 8, 8, 7, 9, 7, 6, 3, 3])

In [247]:
bool_arr = arr_rand > 3

In [249]:
bool_arr

array([ True, False,  True,  True,  True,  True,  True,  True, False,
       False])

In [251]:
arr_rand[bool_arr]

array([5, 8, 8, 7, 9, 7, 6])

In [253]:
# or else we can use this in short hand as below

arr_rand[arr_rand > 6]

array([8, 8, 7, 9, 7])

In [255]:
arr_rand[arr_rand<5]

array([2, 3, 3])